server:
  port: 8083

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    

spring:
  application:
    name: zuul-api-gateway
    
zuul:
  prefix: /api
  routes:
    eureka-server:
      path: /server/**
      url: http://localhost:8081
    eureka-client:
      path: /client/**
      serviceId: EUREKA-CLIENT
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000